name: docker cd
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: docker login
      env:
        USER: ${{ secrets.DOCKER_USERNAME }}
        PASS: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u "$USER" -p "$PASS"
    - name: env setup
      run: test -f .env || cp .env.sample .env
    - name: build images
      run: docker-compose build --no-cache
    - name: docker push
      run: docker-compose push
      
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
	with:
	   host: ${{ secrets.HOST}}
	   username: ${{ secrets.USER}}
	   key: ${{ secrets.KEY }}
	   port: ${{ secrets.PORT }}
	   
	   run: |
	       echo $USER && ls -lart

        


