name: docker cd
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: docker login
      env:
        USER: ${{ secrets.DOCKER_USERNAME }}
        PASS: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u "$USER" -p "$PASS"
    - name: env setup
      run: test -f .env || cp .env.sample .env
    - name: build images
      run: docker-compose build --no-cache
    - name: docker push
      run: docker-compose push
      
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME : ${{ secrets.HOST }}
            USER_NAME : ${{ secrets.USER }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            ls -la
            echo $PWD
            echo $USER
            ls -lart 
	

        


